# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('product_photo', models.FileField(upload_to='')),
            ],
        ),
    ]
